my_project_name/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  
end

my_project_name/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my_project_name/app/models/cat.rb
require 'action_view'
require 'date'

# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  COLORS = %w(black white red blue)
  
  validates :color, inclusion: { in: COLORS}
  validates :sex, inclusion: { in: %w(M F)}
  validates :birth_date, :description, presence: true
  
  def age
    # birth_year = :birth_date.to_s[0..3].to_i
    # todays_year = Date.today.to_s[0..3].to_i

    # todays_year - birth_year 
    time_ago_in_words(birth_date)
  end

  

end

my_project_name/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

my_project_name/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show 
    end
end

my_project_name/app/helpers/application_helper.rb
module ApplicationHelper
end

my_project_name/app/views/cats/index.html.erb
<h1>All Cats</h1>

<ul>
    <% @cats.each do |cat| %>
        <li><a href=" <%= cat_url(cat) %>" ><%=  cat.name %> </a> </li>
    <% end %>
</ul>

my_project_name/app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <tr>
    <td> birth_date </td>
    <td><%= @cat.birth_date %></td>
  </tr>

  <tr>
    <td> color </td>
    <td><%= @cat.color %></td>
  </tr>

  <tr>
    <td> age </td>
    <td><%= @cat.age %></td>
  </tr>

  <tr>
    <td> sex </td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

my_project_name/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProjectName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>